### ISSUE TITLE
Is This really Local? Power values are shown Nan When internet is disconnected.

### ISSUE THREAD

**Issue by ceaswaran** [subzero79/node-red-contrib-tuya-local#28]
I managed to configure this node  in node-red for my PowerMonitoring Plug
It works fine.
I am able to Turn ON/OFF view the Voltage/ Current/Watts value.

But When I disconnect the internet access for the device (Plug). I am able to control (ON/OFF) the device locally thru lan, but not see the Voltage/ Current/Watts values.

**These power values are always Nan when the Internet to the device is disconnected.**
![image](https://user-images.githubusercontent.com/40624146/89209136-57741180-d5db-11ea-800b-59ae773da746.png)

I tried to make the Nodred config simple as below:

![image](https://user-images.githubusercontent.com/40624146/89208826-bb4a0a80-d5da-11ea-87cc-d96f624d9de5.png)

HA Config as follows:
```
switch :
  - platform: mqtt
    name: "3D Printer Tuya Local"
    state_topic: "hass/tlsw01"
    command_topic: "hass/tlsw01/set"
    payload_on: "true"
    payload_off: "false"
    state_on: "true"
    state_off: "false"
    optimistic: false
    qos: 0
    retain: true   

sensor:
   - platform: mqtt
     name: "3D Printer Watts"
     state_topic: "hass/tlsw01/watts"
     unit_of_measurement: W
     value_template: "{{ value | round(1) }}"
   - platform: mqtt
     name: "3D Printer Current"
     state_topic: "hass/tlsw01/amps"
     unit_of_measurement: A
     value_template: "{{ value | round(1) }}"
   - platform: mqtt
     name: "3D Printer Voltage"
     state_topic: "hass/tlsw01/volts"
     unit_of_measurement: V
     value_template: "{{ value | round(1) }}"
```

Please help
